import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import useDebounce from '../hooks/useDebounce';
export interface Notice {
  forename: string;
  date_of_birth: string;
  entity_id: string;
  nationalities: string[];
  name: string;
  _links: Links;
}

export interface Links {
  self: Images;
  images: Images;
  thumbnail: Images;
}
export interface Images {
  href: string;
}
const Home: NextPage = () => {
  const [notices, setNotices] = useState<Notice[]>([]);
  const [search, setSearch] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const debouncedSearch = useDebounce(search, 1000);

  useEffect(() => {
    async function fetchData() {
      setIsLoading(true);
      const data = await fetch(
        `https://ws-public.interpol.int/notices/v1/red?forename=${debouncedSearch}&resultPerPage=160`
      ).then((response) => response.json());

      setNotices(data?._embedded?.notices);
      setIsLoading(false);
    }
    if (debouncedSearch) fetchData();
  }, [debouncedSearch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          type="search"
          placeholder="Search"
          onChange={(e) => setSearch(e.target.value)}
        />
        <br />

        {isLoading && <p>Loading...</p>}

        {/* {JSON.stringify(notices)} */}
        {notices.map((notice, index) => {
          return (
            <div key={index} className={styles.notice}>
              {notice._links?.thumbnail?.href && (
                <Image
                  src={notice._links?.thumbnail?.href}
                  width="100px"
                  height="100px"
                  alt={notice.name}
                />
              )}
              <div className={styles.notice_body}>
                <p>
                  {notice.forename} {notice.name}
                </p>
              </div>
            </div>
          );
        })}
      </main>
    </div>
  );
};

export default Home;
